name: "rsyslog"
description: "rsyslog addon"
version: "2.7"
slug: "rsyslog"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  514/udp: 514
map:
  - share:rw
  - media:rw
hassio_api: true
homeassistant_api: false
host_network: false

options:
  log_folder: null
schema:
  log_folder: str
